In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print('array a:',a)

array a: [1 2 3]


In [4]:
b =np.arange(0,10,2)
print("array b:",b)

array b: [0 2 4 6 8]


In [5]:
c =np.arange(1,10,2)
print("array c:",c)

array c: [1 3 5 7 9]


In [6]:
d = np.zeros((2,3),dtype=int)
d

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
e = np.ones((3,2),dtype=int)
e

array([[1, 1],
       [1, 1],
       [1, 1]])

In [8]:
f = np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
a1 = np.array([1,2,3])

In [10]:
resha= np.reshape(a1,(3,1))
resha

array([[1],
       [2],
       [3]])

In [11]:
f1 = np.array([[1,2],[3,4]])
flat = np.ravel(f1)

In [12]:
flat

array([1, 2, 3, 4])

In [13]:
el = np.array([[1,2],[3,4]])
trans = np.transpose(el)
trans

array([[1, 3],
       [2, 4]])

In [14]:
a2 = np.array([1,2])
b2 = np.array([3,4])
strack = np.vstack([a2,b2])
strack

array([[1, 2],
       [3, 4]])

In [18]:
arr = np.array([[1,2,3],[1,2,3]])
print(arr)
arr

[[1 2 3]
 [1 2 3]]


array([[1, 2, 3],
       [1, 2, 3]])

In [19]:
type(arr)

numpy.ndarray

In [21]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [28]:
np.arange(1,10,.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [51]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [54]:
np.zeros((3,3) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [60]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [311]:
arr = np.random.randn(1000 )
print(arr.max())
print(arr.min())
np.bincount(arr)

2.896247779832271
-3.4975083934185234


TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [222]:
arr.max()

np.float64(3.5334784141107645)

In [312]:
np.random.rand(1,4)

array([[0.45229941, 0.53708356, 0.42090997, 0.2143085 ]])

In [314]:
np.random.randint(6,2,4)

ValueError: low >= high

In [359]:
np.random.randint(0,5,5)

array([4, 1, 3, 2, 4], dtype=int32)

In [366]:
copArr = np.array([1,1,1])
copArr
arr = np.array([0,0,0])
i = 0

In [364]:
while arr != copArr:
    arr = np.random.randint(0,5,5)
    i +=1

print(i)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [369]:
if np.array_equal(arr, copArr):
    print("Match!")
    print(i)

else:
    print("No match!")
    arr = np.random.randint(0,5,5)
    i +=1
    
print(i)



No match!
3


In [421]:

copArr = np.array([1,1,1,1,1,1,1,1,1,1])
arr = np.array([0, 0, 0, 0, 0])
i = 0

while not np.array_equal(arr, copArr):
    arr = np.random.randint(0, 5, 10)
    i += 1

print(i)


KeyboardInterrupt: 

In [424]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
arr = np.arange(1,10).reshape(3,3)

ValueError: cannot reshape array of size 3 into shape (3,3)

In [438]:
arr = np.arange(1,4)
arr.reshape(3,1)

array([[1],
       [2],
       [3]])

In [441]:
arr.reshape(3,1)

array([[1],
       [2],
       [3]])

In [442]:
np.arange(3)

array([0, 1, 2])

In [456]:
np.arange(1,13).reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [457]:
arr= np.random.randint(10,20,(4,5))

In [458]:
arr

array([[16, 14, 17, 17, 12],
       [15, 14, 13, 11, 18],
       [14, 15, 12, 15, 15],
       [18, 17, 18, 10, 19]], dtype=int32)

In [459]:
arr[:]

array([[16, 14, 17, 17, 12],
       [15, 14, 13, 11, 18],
       [14, 15, 12, 15, 15],
       [18, 17, 18, 10, 19]], dtype=int32)

In [463]:
arr.reshape(1,-1)

array([[16, 14, 17, 17, 12, 15, 14, 13, 11, 18, 14, 15, 12, 15, 15, 18,
        17, 18, 10, 19]], dtype=int32)

In [464]:
arr

array([[16, 14, 17, 17, 12],
       [15, 14, 13, 11, 18],
       [14, 15, 12, 15, 15],
       [18, 17, 18, 10, 19]], dtype=int32)

In [465]:
a =arr

In [466]:
a[1:3]

array([[15, 14, 13, 11, 18],
       [14, 15, 12, 15, 15]], dtype=int32)

In [467]:
a

array([[16, 14, 17, 17, 12],
       [15, 14, 13, 11, 18],
       [14, 15, 12, 15, 15],
       [18, 17, 18, 10, 19]], dtype=int32)

In [478]:
a[1:-0]

array([], shape=(0, 5), dtype=int32)