In [14]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print('array a:',a)

array a: [1 2 3]


In [4]:
b =np.arange(0,10,2)
print("array b:",b)

array b: [0 2 4 6 8]


In [5]:
c =np.arange(1,10,2)
print("array c:",c)

array c: [1 3 5 7 9]


In [9]:
d = np.zeros((2,3),dtype=int)
d

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
e = np.ones((3,2),dtype=int)
e

array([[1, 1],
       [1, 1],
       [1, 1]])

In [13]:
f = np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
a1 = np.array([1,2,3])

In [19]:
resha= np.reshape(a1,(3,1))
resha

array([[1],
       [2],
       [3]])

In [20]:
f1 = np.array([[1,2],[3,4]])
flat = np.ravel(f1)

In [21]:
flat

array([1, 2, 3, 4])

In [23]:
el = np.array([[1,2],[3,4]])
trans = np.transpose(el)
trans

array([[1, 3],
       [2, 4]])

In [26]:
a2 = np.array([1,2])
b2 = np.array([3,4])
strack = np.vstack([a2,b2])
strack

array([[1, 2],
       [3, 4]])